### ISSUE TITLE
Pop up windows open not centred (top right corner)

### ISSUE THREAD

**Issue by jimblue** [MaxArt2501/share-this#17]
Hi @MaxArt2501 !

Just notice that pop up windows is not centred.

I'm using an other sharing JS lib that does sizing and centering:

http://www.ellison.rocks/sharer.js/

Maybe you could reuse this code?

Thank you

**Comment by MaxArt2501** [comment]
Isn't this basically the same of issue #10 ?

Anyway, no, the library you linked looks quite different in terms of DOM interaction.

**Comment by jimblue** [comment]
I do think so.
I'm talking about the popup window (where twitter / facebook or other sharer appear).

**Comment by MaxArt2501** [comment]
This problem is relative to sharers which, provided as they are, simply open a new window/tab with an anchor with `target="_blank"`, and thus they're positioned automatically by the browser.

Sharers are provided as examples and are not meant to be core parts of the library. If you want to have more control about what happens what the user clicks on a sharing button, I suggest to create your own sharer setting `href` attribute to `"javascript:;"` from the anchor in the `render` method, and providing a [`action` method ](https://github.com/MaxArt2501/share-this#actionevent-item-optional) that opens your centered window. For example:

```javascript
action() {
  // This will open a 640x400 window centered on the screen
  const width = 640;
  const height = 400;
  const left = screen.availLeft + (screen.availWidth - width) / 2;
  const top = screen.availTop + (screen.availHeight - height) / 2;
  window.open('https://url', 'foo', `width=${width},height=${height},left=${left},top=${top}`);
}
```
(Fair warning: I actually haven't tested this code.)

Have a look at the ["speaker sharer"](https://maxart2501.github.io/share-this/dist/sharers/speakers.js) from the project page.

**Comment by jimblue** [comment]
Thanks to your advice @MaxArt2501 I've found a way to center the popup windows! 👍
