### ISSUE TITLE
Disabling this as a user

### ISSUE THREAD

**Issue by mattolson93** [MaxArt2501/share-this#47]
Hello, I am a computer scientist who likes to highlight text of articles as I read them (similar to using my finger while reading a book). I do not like this extension and would like to disable it on my web-browser permanently. While I am technically savvy enough to add a rule on ublock-origin to stop this popup, I doubt most web-users are. 

While I realize a global blocking rule is not feasible, I would love to have a little "x" to click on the first share-this popup that lets me disable this feature for whatever website, hopefully larger websites would keep this feature enabled as a positive user experience.

**Comment by MaxArt2501** [comment]
I perfectly understand your point of view, and actually *I do find* my own library annoying. (I was tasked to write it and I released it as open source, because I had the chance... That's how this package was born.)

But I think it's up to the the developers that use it that should take care of the user experience. This library offers all the necessary to implement such feature, e.g. with a custom "sharer".

I'll consider adding such sharer, perhaps in the docs page.
